/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// HotelCancellationResponseBooking
    /// </summary>
    [DataContract]
        public partial class HotelCancellationResponseBooking :  IEquatable<HotelCancellationResponseBooking>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HotelCancellationResponseBooking" /> class.
        /// </summary>
        /// <param name="reference">reference.</param>
        /// <param name="status">status.</param>
        /// <param name="bookingDate">bookingDate.</param>
        /// <param name="comments">comments.</param>
        /// <param name="totalPrice">totalPrice.</param>
        /// <param name="currency">currency.</param>
        /// <param name="checkIn">checkIn.</param>
        /// <param name="checkOut">checkOut.</param>
        /// <param name="holder">holder.</param>
        /// <param name="hotel">hotel.</param>
        public HotelCancellationResponseBooking(string reference = default(string), string status = default(string), DateTime? bookingDate = default(DateTime?), int? comments = default(int?), int? totalPrice = default(int?), string currency = default(string), DateTime? checkIn = default(DateTime?), DateTime? checkOut = default(DateTime?), HotelConfirmationRequestHolder holder = default(HotelConfirmationRequestHolder), HotelCancellationResponseBookingHotel hotel = default(HotelCancellationResponseBookingHotel))
        {
            this.Reference = reference;
            this.Status = status;
            this.BookingDate = bookingDate;
            this.Comments = comments;
            this.TotalPrice = totalPrice;
            this.Currency = currency;
            this.CheckIn = checkIn;
            this.CheckOut = checkOut;
            this.Holder = holder;
            this.Hotel = hotel;
        }
        
        /// <summary>
        /// Gets or Sets Reference
        /// </summary>
        [DataMember(Name="reference", EmitDefaultValue=false)]
        public string Reference { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets BookingDate
        /// </summary>
        [DataMember(Name="bookingDate", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? BookingDate { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public int? Comments { get; set; }

        /// <summary>
        /// Gets or Sets TotalPrice
        /// </summary>
        [DataMember(Name="totalPrice", EmitDefaultValue=false)]
        public int? TotalPrice { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name="currency", EmitDefaultValue=false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets CheckIn
        /// </summary>
        [DataMember(Name="checkIn", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? CheckIn { get; set; }

        /// <summary>
        /// Gets or Sets CheckOut
        /// </summary>
        [DataMember(Name="checkOut", EmitDefaultValue=false)]
        [JsonConverter(typeof(SwaggerDateConverter))]
        public DateTime? CheckOut { get; set; }

        /// <summary>
        /// Gets or Sets Holder
        /// </summary>
        [DataMember(Name="holder", EmitDefaultValue=false)]
        public HotelConfirmationRequestHolder Holder { get; set; }

        /// <summary>
        /// Gets or Sets Hotel
        /// </summary>
        [DataMember(Name="hotel", EmitDefaultValue=false)]
        public HotelCancellationResponseBookingHotel Hotel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HotelCancellationResponseBooking {\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  BookingDate: ").Append(BookingDate).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  TotalPrice: ").Append(TotalPrice).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  CheckIn: ").Append(CheckIn).Append("\n");
            sb.Append("  CheckOut: ").Append(CheckOut).Append("\n");
            sb.Append("  Holder: ").Append(Holder).Append("\n");
            sb.Append("  Hotel: ").Append(Hotel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HotelCancellationResponseBooking);
        }

        /// <summary>
        /// Returns true if HotelCancellationResponseBooking instances are equal
        /// </summary>
        /// <param name="input">Instance of HotelCancellationResponseBooking to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HotelCancellationResponseBooking input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Reference == input.Reference ||
                    (this.Reference != null &&
                    this.Reference.Equals(input.Reference))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.BookingDate == input.BookingDate ||
                    (this.BookingDate != null &&
                    this.BookingDate.Equals(input.BookingDate))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.TotalPrice == input.TotalPrice ||
                    (this.TotalPrice != null &&
                    this.TotalPrice.Equals(input.TotalPrice))
                ) && 
                (
                    this.Currency == input.Currency ||
                    (this.Currency != null &&
                    this.Currency.Equals(input.Currency))
                ) && 
                (
                    this.CheckIn == input.CheckIn ||
                    (this.CheckIn != null &&
                    this.CheckIn.Equals(input.CheckIn))
                ) && 
                (
                    this.CheckOut == input.CheckOut ||
                    (this.CheckOut != null &&
                    this.CheckOut.Equals(input.CheckOut))
                ) && 
                (
                    this.Holder == input.Holder ||
                    (this.Holder != null &&
                    this.Holder.Equals(input.Holder))
                ) && 
                (
                    this.Hotel == input.Hotel ||
                    (this.Hotel != null &&
                    this.Hotel.Equals(input.Hotel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Reference != null)
                    hashCode = hashCode * 59 + this.Reference.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.BookingDate != null)
                    hashCode = hashCode * 59 + this.BookingDate.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.TotalPrice != null)
                    hashCode = hashCode * 59 + this.TotalPrice.GetHashCode();
                if (this.Currency != null)
                    hashCode = hashCode * 59 + this.Currency.GetHashCode();
                if (this.CheckIn != null)
                    hashCode = hashCode * 59 + this.CheckIn.GetHashCode();
                if (this.CheckOut != null)
                    hashCode = hashCode * 59 + this.CheckOut.GetHashCode();
                if (this.Holder != null)
                    hashCode = hashCode * 59 + this.Holder.GetHashCode();
                if (this.Hotel != null)
                    hashCode = hashCode * 59 + this.Hotel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
