/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// HotelAvailabilityRequestOccupancies
    /// </summary>
    [DataContract]
        public partial class HotelAvailabilityRequestOccupancies :  IEquatable<HotelAvailabilityRequestOccupancies>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HotelAvailabilityRequestOccupancies" /> class.
        /// </summary>
        /// <param name="adults">adults.</param>
        /// <param name="children">children.</param>
        /// <param name="paxes">paxes.</param>
        public HotelAvailabilityRequestOccupancies(int? adults = default(int?), int? children = default(int?), List<HotelAvailabilityRequestPaxes> paxes = default(List<HotelAvailabilityRequestPaxes>))
        {
            this.Adults = adults;
            this.Children = children;
            this.Paxes = paxes;
        }
        
        /// <summary>
        /// Gets or Sets Adults
        /// </summary>
        [DataMember(Name="adults", EmitDefaultValue=false)]
        public int? Adults { get; set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [DataMember(Name="children", EmitDefaultValue=false)]
        public int? Children { get; set; }

        /// <summary>
        /// Gets or Sets Paxes
        /// </summary>
        [DataMember(Name="paxes", EmitDefaultValue=false)]
        public List<HotelAvailabilityRequestPaxes> Paxes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HotelAvailabilityRequestOccupancies {\n");
            sb.Append("  Adults: ").Append(Adults).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Paxes: ").Append(Paxes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HotelAvailabilityRequestOccupancies);
        }

        /// <summary>
        /// Returns true if HotelAvailabilityRequestOccupancies instances are equal
        /// </summary>
        /// <param name="input">Instance of HotelAvailabilityRequestOccupancies to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HotelAvailabilityRequestOccupancies input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Adults == input.Adults ||
                    (this.Adults != null &&
                    this.Adults.Equals(input.Adults))
                ) && 
                (
                    this.Children == input.Children ||
                    (this.Children != null &&
                    this.Children.Equals(input.Children))
                ) && 
                (
                    this.Paxes == input.Paxes ||
                    this.Paxes != null &&
                    input.Paxes != null &&
                    this.Paxes.SequenceEqual(input.Paxes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Adults != null)
                    hashCode = hashCode * 59 + this.Adults.GetHashCode();
                if (this.Children != null)
                    hashCode = hashCode * 59 + this.Children.GetHashCode();
                if (this.Paxes != null)
                    hashCode = hashCode * 59 + this.Paxes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
