/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightAirline
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightAirlineTests
    {
        // TODO uncomment below to declare an instance variable for FlightAirline
        //private FlightAirline instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightAirline
            //instance = new FlightAirline();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightAirline
        /// </summary>
        [Test]
        public void FlightAirlineInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightAirline
            //Assert.IsInstanceOfType<FlightAirline> (instance, "variable 'instance' is a FlightAirline");
        }


        /// <summary>
        /// Test the property 'Airline'
        /// </summary>
        [Test]
        public void AirlineTest()
        {
            // TODO unit test for the property 'Airline'
        }
        /// <summary>
        /// Test the property 'BestPrice'
        /// </summary>
        [Test]
        public void BestPriceTest()
        {
            // TODO unit test for the property 'BestPrice'
        }
        /// <summary>
        /// Test the property 'Callsign'
        /// </summary>
        [Test]
        public void CallsignTest()
        {
            // TODO unit test for the property 'Callsign'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'CountryOfOrigin'
        /// </summary>
        [Test]
        public void CountryOfOriginTest()
        {
            // TODO unit test for the property 'CountryOfOrigin'
        }
        /// <summary>
        /// Test the property 'Iata'
        /// </summary>
        [Test]
        public void IataTest()
        {
            // TODO unit test for the property 'Iata'
        }
        /// <summary>
        /// Test the property 'Icao'
        /// </summary>
        [Test]
        public void IcaoTest()
        {
            // TODO unit test for the property 'Icao'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
