/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightBookingArrivalLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightBookingArrivalLocationTests
    {
        // TODO uncomment below to declare an instance variable for FlightBookingArrivalLocation
        //private FlightBookingArrivalLocation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightBookingArrivalLocation
            //instance = new FlightBookingArrivalLocation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightBookingArrivalLocation
        /// </summary>
        [Test]
        public void FlightBookingArrivalLocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightBookingArrivalLocation
            //Assert.IsInstanceOfType<FlightBookingArrivalLocation> (instance, "variable 'instance' is a FlightBookingArrivalLocation");
        }


        /// <summary>
        /// Test the property 'Airport'
        /// </summary>
        [Test]
        public void AirportTest()
        {
            // TODO unit test for the property 'Airport'
        }
        /// <summary>
        /// Test the property 'CityAndCountry'
        /// </summary>
        [Test]
        public void CityAndCountryTest()
        {
            // TODO unit test for the property 'CityAndCountry'
        }

    }

}
