/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightFareResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightFareResponseTests
    {
        // TODO uncomment below to declare an instance variable for FlightFareResponse
        //private FlightFareResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightFareResponse
            //instance = new FlightFareResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightFareResponse
        /// </summary>
        [Test]
        public void FlightFareResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightFareResponse
            //Assert.IsInstanceOfType<FlightFareResponse> (instance, "variable 'instance' is a FlightFareResponse");
        }


        /// <summary>
        /// Test the property 'Fare'
        /// </summary>
        [Test]
        public void FareTest()
        {
            // TODO unit test for the property 'Fare'
        }

    }

}
