/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightAirport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightAirportTests
    {
        // TODO uncomment below to declare an instance variable for FlightAirport
        //private FlightAirport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightAirport
            //instance = new FlightAirport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightAirport
        /// </summary>
        [Test]
        public void FlightAirportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightAirport
            //Assert.IsInstanceOfType<FlightAirport> (instance, "variable 'instance' is a FlightAirport");
        }


        /// <summary>
        /// Test the property 'CityCode'
        /// </summary>
        [Test]
        public void CityCodeTest()
        {
            // TODO unit test for the property 'CityCode'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Test]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'CountryName'
        /// </summary>
        [Test]
        public void CountryNameTest()
        {
            // TODO unit test for the property 'CountryName'
        }
        /// <summary>
        /// Test the property 'Display'
        /// </summary>
        [Test]
        public void DisplayTest()
        {
            // TODO unit test for the property 'Display'
        }
        /// <summary>
        /// Test the property 'Iata'
        /// </summary>
        [Test]
        public void IataTest()
        {
            // TODO unit test for the property 'Iata'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'NumberOfAirportsInTheCity'
        /// </summary>
        [Test]
        public void NumberOfAirportsInTheCityTest()
        {
            // TODO unit test for the property 'NumberOfAirportsInTheCity'
        }

    }

}
