/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightDetailedPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightDetailedPriceTests
    {
        // TODO uncomment below to declare an instance variable for FlightDetailedPrice
        //private FlightDetailedPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightDetailedPrice
            //instance = new FlightDetailedPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightDetailedPrice
        /// </summary>
        [Test]
        public void FlightDetailedPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightDetailedPrice
            //Assert.IsInstanceOfType<FlightDetailedPrice> (instance, "variable 'instance' is a FlightDetailedPrice");
        }


        /// <summary>
        /// Test the property 'AdtPrice'
        /// </summary>
        [Test]
        public void AdtPriceTest()
        {
            // TODO unit test for the property 'AdtPrice'
        }
        /// <summary>
        /// Test the property 'ChdPrice'
        /// </summary>
        [Test]
        public void ChdPriceTest()
        {
            // TODO unit test for the property 'ChdPrice'
        }
        /// <summary>
        /// Test the property 'InfPrice'
        /// </summary>
        [Test]
        public void InfPriceTest()
        {
            // TODO unit test for the property 'InfPrice'
        }
        /// <summary>
        /// Test the property 'InsPrice'
        /// </summary>
        [Test]
        public void InsPriceTest()
        {
            // TODO unit test for the property 'InsPrice'
        }
        /// <summary>
        /// Test the property 'SrcPrice'
        /// </summary>
        [Test]
        public void SrcPriceTest()
        {
            // TODO unit test for the property 'SrcPrice'
        }
        /// <summary>
        /// Test the property 'YthPrice'
        /// </summary>
        [Test]
        public void YthPriceTest()
        {
            // TODO unit test for the property 'YthPrice'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'AgencyFees'
        /// </summary>
        [Test]
        public void AgencyFeesTest()
        {
            // TODO unit test for the property 'AgencyFees'
        }
        /// <summary>
        /// Test the property 'AgencyFeesPerPax'
        /// </summary>
        [Test]
        public void AgencyFeesPerPaxTest()
        {
            // TODO unit test for the property 'AgencyFeesPerPax'
        }
        /// <summary>
        /// Test the property 'AgencyMarkup'
        /// </summary>
        [Test]
        public void AgencyMarkupTest()
        {
            // TODO unit test for the property 'AgencyMarkup'
        }
        /// <summary>
        /// Test the property 'BaseFare'
        /// </summary>
        [Test]
        public void BaseFareTest()
        {
            // TODO unit test for the property 'BaseFare'
        }
        /// <summary>
        /// Test the property 'PaxNumber'
        /// </summary>
        [Test]
        public void PaxNumberTest()
        {
            // TODO unit test for the property 'PaxNumber'
        }
        /// <summary>
        /// Test the property 'PlatformFees'
        /// </summary>
        [Test]
        public void PlatformFeesTest()
        {
            // TODO unit test for the property 'PlatformFees'
        }
        /// <summary>
        /// Test the property 'PlatformFeesPerPax'
        /// </summary>
        [Test]
        public void PlatformFeesPerPaxTest()
        {
            // TODO unit test for the property 'PlatformFeesPerPax'
        }
        /// <summary>
        /// Test the property 'PlatformMarkup'
        /// </summary>
        [Test]
        public void PlatformMarkupTest()
        {
            // TODO unit test for the property 'PlatformMarkup'
        }
        /// <summary>
        /// Test the property 'ServiceAmountPerPax'
        /// </summary>
        [Test]
        public void ServiceAmountPerPaxTest()
        {
            // TODO unit test for the property 'ServiceAmountPerPax'
        }
        /// <summary>
        /// Test the property 'ServiceFees'
        /// </summary>
        [Test]
        public void ServiceFeesTest()
        {
            // TODO unit test for the property 'ServiceFees'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
        /// <summary>
        /// Test the property 'TotalInRequestedCurrency'
        /// </summary>
        [Test]
        public void TotalInRequestedCurrencyTest()
        {
            // TODO unit test for the property 'TotalInRequestedCurrency'
        }
        /// <summary>
        /// Test the property 'TotalPlatform'
        /// </summary>
        [Test]
        public void TotalPlatformTest()
        {
            // TODO unit test for the property 'TotalPlatform'
        }
        /// <summary>
        /// Test the property 'TotalProvider'
        /// </summary>
        [Test]
        public void TotalProviderTest()
        {
            // TODO unit test for the property 'TotalProvider'
        }

    }

}
