/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightAvailability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightAvailabilityTests
    {
        // TODO uncomment below to declare an instance variable for FlightAvailability
        //private FlightAvailability instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightAvailability
            //instance = new FlightAvailability();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightAvailability
        /// </summary>
        [Test]
        public void FlightAvailabilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightAvailability
            //Assert.IsInstanceOfType<FlightAvailability> (instance, "variable 'instance' is a FlightAvailability");
        }


        /// <summary>
        /// Test the property 'AirlineDictionary'
        /// </summary>
        [Test]
        public void AirlineDictionaryTest()
        {
            // TODO unit test for the property 'AirlineDictionary'
        }
        /// <summary>
        /// Test the property 'AirportDictionary'
        /// </summary>
        [Test]
        public void AirportDictionaryTest()
        {
            // TODO unit test for the property 'AirportDictionary'
        }
        /// <summary>
        /// Test the property 'BestPrice'
        /// </summary>
        [Test]
        public void BestPriceTest()
        {
            // TODO unit test for the property 'BestPrice'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'FlightNeedExchangeDocuments'
        /// </summary>
        [Test]
        public void FlightNeedExchangeDocumentsTest()
        {
            // TODO unit test for the property 'FlightNeedExchangeDocuments'
        }
        /// <summary>
        /// Test the property 'GroupOfFlights'
        /// </summary>
        [Test]
        public void GroupOfFlightsTest()
        {
            // TODO unit test for the property 'GroupOfFlights'
        }
        /// <summary>
        /// Test the property 'IsDomesticFlight'
        /// </summary>
        [Test]
        public void IsDomesticFlightTest()
        {
            // TODO unit test for the property 'IsDomesticFlight'
        }
        /// <summary>
        /// Test the property 'Recommendations'
        /// </summary>
        [Test]
        public void RecommendationsTest()
        {
            // TODO unit test for the property 'Recommendations'
        }

    }

}
