/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightAvailabilitySegment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightAvailabilitySegmentTests
    {
        // TODO uncomment below to declare an instance variable for FlightAvailabilitySegment
        //private FlightAvailabilitySegment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightAvailabilitySegment
            //instance = new FlightAvailabilitySegment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightAvailabilitySegment
        /// </summary>
        [Test]
        public void FlightAvailabilitySegmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightAvailabilitySegment
            //Assert.IsInstanceOfType<FlightAvailabilitySegment> (instance, "variable 'instance' is a FlightAvailabilitySegment");
        }


        /// <summary>
        /// Test the property 'Arrival'
        /// </summary>
        [Test]
        public void ArrivalTest()
        {
            // TODO unit test for the property 'Arrival'
        }
        /// <summary>
        /// Test the property 'DayDifference'
        /// </summary>
        [Test]
        public void DayDifferenceTest()
        {
            // TODO unit test for the property 'DayDifference'
        }
        /// <summary>
        /// Test the property 'Departure'
        /// </summary>
        [Test]
        public void DepartureTest()
        {
            // TODO unit test for the property 'Departure'
        }
        /// <summary>
        /// Test the property 'EquipmentType'
        /// </summary>
        [Test]
        public void EquipmentTypeTest()
        {
            // TODO unit test for the property 'EquipmentType'
        }
        /// <summary>
        /// Test the property 'FlightOrtrainNumber'
        /// </summary>
        [Test]
        public void FlightOrtrainNumberTest()
        {
            // TODO unit test for the property 'FlightOrtrainNumber'
        }
        /// <summary>
        /// Test the property 'MarketingCarrier'
        /// </summary>
        [Test]
        public void MarketingCarrierTest()
        {
            // TODO unit test for the property 'MarketingCarrier'
        }
        /// <summary>
        /// Test the property 'OperatingCarrier'
        /// </summary>
        [Test]
        public void OperatingCarrierTest()
        {
            // TODO unit test for the property 'OperatingCarrier'
        }

    }

}
