/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightBaseTraveller
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightBaseTravellerTests
    {
        // TODO uncomment below to declare an instance variable for FlightBaseTraveller
        //private FlightBaseTraveller instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightBaseTraveller
            //instance = new FlightBaseTraveller();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightBaseTraveller
        /// </summary>
        [Test]
        public void FlightBaseTravellerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightBaseTraveller
            //Assert.IsInstanceOfType<FlightBaseTraveller> (instance, "variable 'instance' is a FlightBaseTraveller");
        }


        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Test]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Test]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'PassportExpirationDate'
        /// </summary>
        [Test]
        public void PassportExpirationDateTest()
        {
            // TODO unit test for the property 'PassportExpirationDate'
        }
        /// <summary>
        /// Test the property 'PassportNumber'
        /// </summary>
        [Test]
        public void PassportNumberTest()
        {
            // TODO unit test for the property 'PassportNumber'
        }
        /// <summary>
        /// Test the property 'Sex'
        /// </summary>
        [Test]
        public void SexTest()
        {
            // TODO unit test for the property 'Sex'
        }

    }

}
