/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightTraveller
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightTravellerTests
    {
        // TODO uncomment below to declare an instance variable for FlightTraveller
        //private FlightTraveller instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightTraveller
            //instance = new FlightTraveller();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightTraveller
        /// </summary>
        [Test]
        public void FlightTravellerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightTraveller
            //Assert.IsInstanceOfType<FlightTraveller> (instance, "variable 'instance' is a FlightTraveller");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'SpecialService'
        /// </summary>
        [Test]
        public void SpecialServiceTest()
        {
            // TODO unit test for the property 'SpecialService'
        }
        /// <summary>
        /// Test the property 'Infant'
        /// </summary>
        [Test]
        public void InfantTest()
        {
            // TODO unit test for the property 'Infant'
        }

    }

}
