/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightPaxTypePrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightPaxTypePriceTests
    {
        // TODO uncomment below to declare an instance variable for FlightPaxTypePrice
        //private FlightPaxTypePrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightPaxTypePrice
            //instance = new FlightPaxTypePrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightPaxTypePrice
        /// </summary>
        [Test]
        public void FlightPaxTypePriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightPaxTypePrice
            //Assert.IsInstanceOfType<FlightPaxTypePrice> (instance, "variable 'instance' is a FlightPaxTypePrice");
        }


        /// <summary>
        /// Test the property 'AgencyMarkup'
        /// </summary>
        [Test]
        public void AgencyMarkupTest()
        {
            // TODO unit test for the property 'AgencyMarkup'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'PlatformMarkup'
        /// </summary>
        [Test]
        public void PlatformMarkupTest()
        {
            // TODO unit test for the property 'PlatformMarkup'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Test]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
