/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FlightBookingSegments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FlightBookingSegmentsTests
    {
        // TODO uncomment below to declare an instance variable for FlightBookingSegments
        //private FlightBookingSegments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FlightBookingSegments
            //instance = new FlightBookingSegments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FlightBookingSegments
        /// </summary>
        [Test]
        public void FlightBookingSegmentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FlightBookingSegments
            //Assert.IsInstanceOfType<FlightBookingSegments> (instance, "variable 'instance' is a FlightBookingSegments");
        }


        /// <summary>
        /// Test the property 'ArrivalTerminal'
        /// </summary>
        [Test]
        public void ArrivalTerminalTest()
        {
            // TODO unit test for the property 'ArrivalTerminal'
        }
        /// <summary>
        /// Test the property 'ArrivalDate'
        /// </summary>
        [Test]
        public void ArrivalDateTest()
        {
            // TODO unit test for the property 'ArrivalDate'
        }
        /// <summary>
        /// Test the property 'ArrivalLocation'
        /// </summary>
        [Test]
        public void ArrivalLocationTest()
        {
            // TODO unit test for the property 'ArrivalLocation'
        }
        /// <summary>
        /// Test the property 'ArrivalTime'
        /// </summary>
        [Test]
        public void ArrivalTimeTest()
        {
            // TODO unit test for the property 'ArrivalTime'
        }
        /// <summary>
        /// Test the property 'BaggageInfo'
        /// </summary>
        [Test]
        public void BaggageInfoTest()
        {
            // TODO unit test for the property 'BaggageInfo'
        }
        /// <summary>
        /// Test the property 'BookingClass'
        /// </summary>
        [Test]
        public void BookingClassTest()
        {
            // TODO unit test for the property 'BookingClass'
        }
        /// <summary>
        /// Test the property 'BoundId'
        /// </summary>
        [Test]
        public void BoundIdTest()
        {
            // TODO unit test for the property 'BoundId'
        }
        /// <summary>
        /// Test the property 'Carrier'
        /// </summary>
        [Test]
        public void CarrierTest()
        {
            // TODO unit test for the property 'Carrier'
        }
        /// <summary>
        /// Test the property 'DepartureTerminal'
        /// </summary>
        [Test]
        public void DepartureTerminalTest()
        {
            // TODO unit test for the property 'DepartureTerminal'
        }
        /// <summary>
        /// Test the property 'DepartureDate'
        /// </summary>
        [Test]
        public void DepartureDateTest()
        {
            // TODO unit test for the property 'DepartureDate'
        }
        /// <summary>
        /// Test the property 'DepartureLocation'
        /// </summary>
        [Test]
        public void DepartureLocationTest()
        {
            // TODO unit test for the property 'DepartureLocation'
        }
        /// <summary>
        /// Test the property 'DepartureTime'
        /// </summary>
        [Test]
        public void DepartureTimeTest()
        {
            // TODO unit test for the property 'DepartureTime'
        }
        /// <summary>
        /// Test the property 'FlightEquipment'
        /// </summary>
        [Test]
        public void FlightEquipmentTest()
        {
            // TODO unit test for the property 'FlightEquipment'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Test]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
