/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityRequestGeolocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityRequestGeolocationTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityRequestGeolocation
        //private HotelAvailabilityRequestGeolocation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityRequestGeolocation
            //instance = new HotelAvailabilityRequestGeolocation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityRequestGeolocation
        /// </summary>
        [Test]
        public void HotelAvailabilityRequestGeolocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityRequestGeolocation
            //Assert.IsInstanceOfType<HotelAvailabilityRequestGeolocation> (instance, "variable 'instance' is a HotelAvailabilityRequestGeolocation");
        }


        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Radius'
        /// </summary>
        [Test]
        public void RadiusTest()
        {
            // TODO unit test for the property 'Radius'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
