/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelCancellationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelCancellationResponseTests
    {
        // TODO uncomment below to declare an instance variable for HotelCancellationResponse
        //private HotelCancellationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelCancellationResponse
            //instance = new HotelCancellationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelCancellationResponse
        /// </summary>
        [Test]
        public void HotelCancellationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelCancellationResponse
            //Assert.IsInstanceOfType<HotelCancellationResponse> (instance, "variable 'instance' is a HotelCancellationResponse");
        }


        /// <summary>
        /// Test the property 'Booking'
        /// </summary>
        [Test]
        public void BookingTest()
        {
            // TODO unit test for the property 'Booking'
        }
        /// <summary>
        /// Test the property 'Suppliers'
        /// </summary>
        [Test]
        public void SuppliersTest()
        {
            // TODO unit test for the property 'Suppliers'
        }

    }

}
