/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelCheckRatesRequestRooms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelCheckRatesRequestRoomsTests
    {
        // TODO uncomment below to declare an instance variable for HotelCheckRatesRequestRooms
        //private HotelCheckRatesRequestRooms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelCheckRatesRequestRooms
            //instance = new HotelCheckRatesRequestRooms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelCheckRatesRequestRooms
        /// </summary>
        [Test]
        public void HotelCheckRatesRequestRoomsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelCheckRatesRequestRooms
            //Assert.IsInstanceOfType<HotelCheckRatesRequestRooms> (instance, "variable 'instance' is a HotelCheckRatesRequestRooms");
        }


        /// <summary>
        /// Test the property 'RateKey'
        /// </summary>
        [Test]
        public void RateKeyTest()
        {
            // TODO unit test for the property 'RateKey'
        }
        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Test]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }

    }

}
