/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityResponseHotels
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityResponseHotelsTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityResponseHotels
        //private HotelAvailabilityResponseHotels instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityResponseHotels
            //instance = new HotelAvailabilityResponseHotels();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityResponseHotels
        /// </summary>
        [Test]
        public void HotelAvailabilityResponseHotelsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityResponseHotels
            //Assert.IsInstanceOfType<HotelAvailabilityResponseHotels> (instance, "variable 'instance' is a HotelAvailabilityResponseHotels");
        }


        /// <summary>
        /// Test the property 'Hotels'
        /// </summary>
        [Test]
        public void HotelsTest()
        {
            // TODO unit test for the property 'Hotels'
        }
        /// <summary>
        /// Test the property 'CheckIn'
        /// </summary>
        [Test]
        public void CheckInTest()
        {
            // TODO unit test for the property 'CheckIn'
        }
        /// <summary>
        /// Test the property 'CheckOut'
        /// </summary>
        [Test]
        public void CheckOutTest()
        {
            // TODO unit test for the property 'CheckOut'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
