/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityResponseHotelsThemes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityResponseHotelsThemesTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityResponseHotelsThemes
        //private HotelAvailabilityResponseHotelsThemes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityResponseHotelsThemes
            //instance = new HotelAvailabilityResponseHotelsThemes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityResponseHotelsThemes
        /// </summary>
        [Test]
        public void HotelAvailabilityResponseHotelsThemesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityResponseHotelsThemes
            //Assert.IsInstanceOfType<HotelAvailabilityResponseHotelsThemes> (instance, "variable 'instance' is a HotelAvailabilityResponseHotelsThemes");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

    }

}
