/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityResponseHotelsImages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityResponseHotelsImagesTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityResponseHotelsImages
        //private HotelAvailabilityResponseHotelsImages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityResponseHotelsImages
            //instance = new HotelAvailabilityResponseHotelsImages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityResponseHotelsImages
        /// </summary>
        [Test]
        public void HotelAvailabilityResponseHotelsImagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityResponseHotelsImages
            //Assert.IsInstanceOfType<HotelAvailabilityResponseHotelsImages> (instance, "variable 'instance' is a HotelAvailabilityResponseHotelsImages");
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
