/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelConfirmationResponseBookingHotelRooms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelConfirmationResponseBookingHotelRoomsTests
    {
        // TODO uncomment below to declare an instance variable for HotelConfirmationResponseBookingHotelRooms
        //private HotelConfirmationResponseBookingHotelRooms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelConfirmationResponseBookingHotelRooms
            //instance = new HotelConfirmationResponseBookingHotelRooms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelConfirmationResponseBookingHotelRooms
        /// </summary>
        [Test]
        public void HotelConfirmationResponseBookingHotelRoomsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelConfirmationResponseBookingHotelRooms
            //Assert.IsInstanceOfType<HotelConfirmationResponseBookingHotelRooms> (instance, "variable 'instance' is a HotelConfirmationResponseBookingHotelRooms");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RateKey'
        /// </summary>
        [Test]
        public void RateKeyTest()
        {
            // TODO unit test for the property 'RateKey'
        }
        /// <summary>
        /// Test the property 'BoardName'
        /// </summary>
        [Test]
        public void BoardNameTest()
        {
            // TODO unit test for the property 'BoardName'
        }
        /// <summary>
        /// Test the property 'BoardCode'
        /// </summary>
        [Test]
        public void BoardCodeTest()
        {
            // TODO unit test for the property 'BoardCode'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Adults'
        /// </summary>
        [Test]
        public void AdultsTest()
        {
            // TODO unit test for the property 'Adults'
        }
        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Test]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }
        /// <summary>
        /// Test the property 'CancellationPolicies'
        /// </summary>
        [Test]
        public void CancellationPoliciesTest()
        {
            // TODO unit test for the property 'CancellationPolicies'
        }
        /// <summary>
        /// Test the property 'Paxes'
        /// </summary>
        [Test]
        public void PaxesTest()
        {
            // TODO unit test for the property 'Paxes'
        }
        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Test]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }

    }

}
