/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelConfirmationRequestPaxes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelConfirmationRequestPaxesTests
    {
        // TODO uncomment below to declare an instance variable for HotelConfirmationRequestPaxes
        //private HotelConfirmationRequestPaxes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelConfirmationRequestPaxes
            //instance = new HotelConfirmationRequestPaxes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelConfirmationRequestPaxes
        /// </summary>
        [Test]
        public void HotelConfirmationRequestPaxesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelConfirmationRequestPaxes
            //Assert.IsInstanceOfType<HotelConfirmationRequestPaxes> (instance, "variable 'instance' is a HotelConfirmationRequestPaxes");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Age'
        /// </summary>
        [Test]
        public void AgeTest()
        {
            // TODO unit test for the property 'Age'
        }
        /// <summary>
        /// Test the property 'Firstname'
        /// </summary>
        [Test]
        public void FirstnameTest()
        {
            // TODO unit test for the property 'Firstname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Test]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

    }

}
