/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelCheckRatesResponseHotelRooms
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelCheckRatesResponseHotelRoomsTests
    {
        // TODO uncomment below to declare an instance variable for HotelCheckRatesResponseHotelRooms
        //private HotelCheckRatesResponseHotelRooms instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelCheckRatesResponseHotelRooms
            //instance = new HotelCheckRatesResponseHotelRooms();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelCheckRatesResponseHotelRooms
        /// </summary>
        [Test]
        public void HotelCheckRatesResponseHotelRoomsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelCheckRatesResponseHotelRooms
            //Assert.IsInstanceOfType<HotelCheckRatesResponseHotelRooms> (instance, "variable 'instance' is a HotelCheckRatesResponseHotelRooms");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }

    }

}
