/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelConfirmationRequestPayment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelConfirmationRequestPaymentTests
    {
        // TODO uncomment below to declare an instance variable for HotelConfirmationRequestPayment
        //private HotelConfirmationRequestPayment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelConfirmationRequestPayment
            //instance = new HotelConfirmationRequestPayment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelConfirmationRequestPayment
        /// </summary>
        [Test]
        public void HotelConfirmationRequestPaymentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelConfirmationRequestPayment
            //Assert.IsInstanceOfType<HotelConfirmationRequestPayment> (instance, "variable 'instance' is a HotelConfirmationRequestPayment");
        }


        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'CcType'
        /// </summary>
        [Test]
        public void CcTypeTest()
        {
            // TODO unit test for the property 'CcType'
        }
        /// <summary>
        /// Test the property 'CcNumber'
        /// </summary>
        [Test]
        public void CcNumberTest()
        {
            // TODO unit test for the property 'CcNumber'
        }
        /// <summary>
        /// Test the property 'CcCode'
        /// </summary>
        [Test]
        public void CcCodeTest()
        {
            // TODO unit test for the property 'CcCode'
        }
        /// <summary>
        /// Test the property 'CcEcpMonth'
        /// </summary>
        [Test]
        public void CcEcpMonthTest()
        {
            // TODO unit test for the property 'CcEcpMonth'
        }
        /// <summary>
        /// Test the property 'CcExpYear'
        /// </summary>
        [Test]
        public void CcExpYearTest()
        {
            // TODO unit test for the property 'CcExpYear'
        }

    }

}
