/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityRequestTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityRequest
        //private HotelAvailabilityRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityRequest
            //instance = new HotelAvailabilityRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityRequest
        /// </summary>
        [Test]
        public void HotelAvailabilityRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityRequest
            //Assert.IsInstanceOfType<HotelAvailabilityRequest> (instance, "variable 'instance' is a HotelAvailabilityRequest");
        }


        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Combination'
        /// </summary>
        [Test]
        public void CombinationTest()
        {
            // TODO unit test for the property 'Combination'
        }
        /// <summary>
        /// Test the property 'Stay'
        /// </summary>
        [Test]
        public void StayTest()
        {
            // TODO unit test for the property 'Stay'
        }
        /// <summary>
        /// Test the property 'Occupancies'
        /// </summary>
        [Test]
        public void OccupanciesTest()
        {
            // TODO unit test for the property 'Occupancies'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Test]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'Geolocation'
        /// </summary>
        [Test]
        public void GeolocationTest()
        {
            // TODO unit test for the property 'Geolocation'
        }

    }

}
