/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelAvailabilityRequestFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelAvailabilityRequestFilterTests
    {
        // TODO uncomment below to declare an instance variable for HotelAvailabilityRequestFilter
        //private HotelAvailabilityRequestFilter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelAvailabilityRequestFilter
            //instance = new HotelAvailabilityRequestFilter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelAvailabilityRequestFilter
        /// </summary>
        [Test]
        public void HotelAvailabilityRequestFilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelAvailabilityRequestFilter
            //Assert.IsInstanceOfType<HotelAvailabilityRequestFilter> (instance, "variable 'instance' is a HotelAvailabilityRequestFilter");
        }


        /// <summary>
        /// Test the property 'MaxHotels'
        /// </summary>
        [Test]
        public void MaxHotelsTest()
        {
            // TODO unit test for the property 'MaxHotels'
        }
        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Test]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }

    }

}
