/* 
 * Algebratec API
 *
 * Learn and test our api with ease
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@algebratec.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HotelCancellationResponseBookingHotel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HotelCancellationResponseBookingHotelTests
    {
        // TODO uncomment below to declare an instance variable for HotelCancellationResponseBookingHotel
        //private HotelCancellationResponseBookingHotel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HotelCancellationResponseBookingHotel
            //instance = new HotelCancellationResponseBookingHotel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HotelCancellationResponseBookingHotel
        /// </summary>
        [Test]
        public void HotelCancellationResponseBookingHotelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HotelCancellationResponseBookingHotel
            //Assert.IsInstanceOfType<HotelCancellationResponseBookingHotel> (instance, "variable 'instance' is a HotelCancellationResponseBookingHotel");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProviderName'
        /// </summary>
        [Test]
        public void ProviderNameTest()
        {
            // TODO unit test for the property 'ProviderName'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Mail'
        /// </summary>
        [Test]
        public void MailTest()
        {
            // TODO unit test for the property 'Mail'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'ZoneCode'
        /// </summary>
        [Test]
        public void ZoneCodeTest()
        {
            // TODO unit test for the property 'ZoneCode'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'ZoneName'
        /// </summary>
        [Test]
        public void ZoneNameTest()
        {
            // TODO unit test for the property 'ZoneName'
        }
        /// <summary>
        /// Test the property 'Rooms'
        /// </summary>
        [Test]
        public void RoomsTest()
        {
            // TODO unit test for the property 'Rooms'
        }
        /// <summary>
        /// Test the property 'Extras'
        /// </summary>
        [Test]
        public void ExtrasTest()
        {
            // TODO unit test for the property 'Extras'
        }

    }

}
